name: Runtests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1', 'nightly']
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
        - uses: actions/checkout@v4
        - uses: julia-actions/setup-julia@latest
          with:
            version: ${{ matrix.julia-version }}
        - uses: julia-actions/julia-buildpkg@latest
        - uses: julia-actions/julia-runtest@latest